version: '3.3'

services:
  mongodb1:
    image: mongo:5.0
    container_name: mongo1
    ports:
      - 27021:27017  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data1:/data/db
    networks:
      - backend

  mongodb2:
    image: mongo:5.0
    container_name: mongo2
    ports:
      - 27022:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data2:/data/db
    networks:
      - backend

networks:
  backend:
    external:
      name: proxy